---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: apt update
      ansible.builtin.shell:
        cmd: apt-get update
      timeout: 300
      register: apt_update_out
      failed_when: apt_update_out.stderr_lines is defined

    - name: Debug output
      ansible.builtin.debug: 
        msg: "{{ apt_update_out.stdout_lines }}"
      when: apt_update_out.stdout_lines is defined

    - name: Perform a dist-upgrade.
      ansible.builtin.shell:
        cmd: apt-get dist-upgrade --auto-remove
      timeout: 1200
      register: apt_upgrade_out
      failed_when: apt_upgrade_out.stderr_lines is defined

    - name: Debug output
      ansible.builtin.debug: 
        msg: "{{ apt_upgrade_out.stdout_lines }}"
      when: apt_upgrade_out.stdout_lines is defined

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes

    - name: Debug output
      ansible.builtin.debug: 
        msg: "{{ apt_upgrade_out.stdout_lines }}"
      when: apt_upgrade_out.stdout_lines is defined
