---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: apt update
      ansible.builtin.shell:
        cmd: apt-get update
      timeout: 300
      register: apt_update_out
      failed_when: apt_update_out.stderr_lines is defined

    - name: Debug output
      ansible.builtin.debug: 
        msg: "{{ apt_update_out.stdout_lines }}"
      when: apt_update_out.stdout_lines is defined

